name: TII Build Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mavlink-router
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: docker/setup-buildx-action@v1

      - name: Build PX4-SITL_gazebo
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.build_test
          push: false
